name: Bug Report
description: Report a bug to help us improve KubeRDE
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy KubeRDE with '...'
        2. Create a workspace with '...'
        3. Access service at '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The service should be accessible at https://...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Got 404 error or connection refused
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - Server
        - Operator
        - Agent
        - Web UI
        - CLI
        - Documentation
        - Deployment/Infrastructure
        - Not sure
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      value: |
        - KubeRDE Version: [e.g., v1.0.0 or commit hash]
        - Kubernetes Version: [e.g., 1.28.0]
        - Kubernetes Platform: [e.g., GKE, EKS, AKS, kind, minikube]
        - Ingress Controller: [e.g., NGINX, Traefik, GCE]
        - Operating System: [e.g., Ubuntu 22.04, macOS 14.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please paste any relevant logs. This will be automatically formatted into code.

        Get logs with:
        ```bash
        kubectl logs -n kuberde deployment/kuberde-server
        kubectl logs -n kuberde deployment/kuberde-operator
        kubectl describe pod -n kuberde <pod-name>
        ```
      render: shell
      placeholder: Paste logs here

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: |
        If applicable, paste relevant configuration (remove sensitive data!)
      render: yaml
      placeholder: |
        # Environment variables
        KUBERDE_PUBLIC_URL: https://kuberde.example.com
        KUBERDE_AGENT_DOMAIN: kuberde.example.com

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, etc.)
      placeholder: Any other information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have removed any sensitive information from logs and configs
          required: true
