name: Documentation Improvement
description: Suggest improvements or report issues in documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - Quick Start Guide
        - Platform Guide (GCP/AWS/Azure/Local)
        - API Documentation
        - Architecture Documentation
        - Configuration Reference
        - Troubleshooting Guide
        - Developer Guide (CLAUDE.md)
        - Contributing Guide
        - Security Documentation
        - Code Comments
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which file or page needs improvement?
      placeholder: e.g., docs/platforms/gcp-gke.md, README.md, line 123
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing information
        - Incorrect/outdated information
        - Unclear explanation
        - Typo or grammar
        - Code example doesn't work
        - Broken link
        - Missing example
        - Poor organization
        - Translation needed
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (copy/paste if possible)
      placeholder: |
        Current text or description of what's there now
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What should it say instead? How can it be improved?
      placeholder: |
        Suggested new text or description of improvement
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why This Change?
      description: Why is this change needed? What problem does it solve?
      placeholder: |
        This would help users by...
        I was confused because...
        This prevents errors when...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Screenshots
        - Related issues
        - External references

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      description: Can you help with this documentation improvement?
      options:
        - label: I can submit a PR with the proposed changes
        - label: I can help review the documentation
        - label: I can provide additional examples or clarifications

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this issue doesn't already exist
          required: true
        - label: I have provided specific location and proposed changes
          required: true
