package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

const sshConfigMarkerBegin = "# BEGIN KubeRDE"
const sshConfigMarkerEnd = "# END KubeRDE"

var (
	configSSHServerURL string
	configSSHWrite     bool
)

var configSSHCmd = &cobra.Command{
	Use:   "config-ssh",
	Short: "Generate SSH config for KubeRDE agents",
	Long: `Generates an SSH ProxyCommand config block that lets you use
standard SSH to connect to any KubeRDE agent:

  ssh kuberde-user-alice-dev

The generated block can be printed to stdout (default) or written
directly into ~/.ssh/config with --write.`,
	Run: func(cmd *cobra.Command, args []string) {
		runConfigSSH()
	},
}

func init() {
	configSSHCmd.Flags().StringVar(&configSSHServerURL, "server", "",
		"KubeRDE server WebSocket URL (e.g. wss://frp.byai.uk) [required]")
	configSSHCmd.Flags().BoolVar(&configSSHWrite, "write", false,
		"Write the config block into ~/.ssh/config (replaces any existing KubeRDE block)")
	_ = configSSHCmd.MarkFlagRequired("server")
	rootCmd.AddCommand(configSSHCmd)
}

func runConfigSSH() {
	// Persist the server URL so `kuberde-cli connect <agentID>` can work
	// without a full WebSocket URL.
	if err := saveServerURL(configSSHServerURL); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not save server URL: %v\n", err)
	}

	block := buildSSHConfigBlock(configSSHServerURL)

	if !configSSHWrite {
		fmt.Print(block)
		return
	}

	if err := writeSSHConfig(block); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing ~/.ssh/config: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintln(os.Stderr, "✓ ~/.ssh/config updated with KubeRDE block.")
	fmt.Fprintln(os.Stderr, "  Connect with:  ssh kuberde-<agent-id>")
}

// saveServerURL writes the server URL to ~/.kuberde/server so that
// `kuberde-cli connect <agentID>` can resolve the full WebSocket URL.
func saveServerURL(serverURL string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	dir := filepath.Join(home, ".kuberde")
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "server"), []byte(serverURL), 0600)
}

// LoadServerURL reads the persisted server URL from ~/.kuberde/server.
func LoadServerURL() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(filepath.Join(home, ".kuberde", "server"))
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}

// buildSSHConfigBlock returns the SSH config stanza for KubeRDE agents.
//
// SSH hostname convention: <agentID>
//   Agent IDs start with "kuberde-", e.g. "kuberde-agent-admin-abc-ssh-8a37f662"
//   so "Host kuberde-*" matches them directly.
//
// The ProxyCommand passes %n (the full SSH hostname = agent ID) to `kuberde-cli connect`,
// which resolves the server URL from ~/.kuberde/server.
func buildSSHConfigBlock(serverURL string) string {
	serverURL = strings.TrimSuffix(serverURL, "/ws")

	return fmt.Sprintf(`%s
# Generated by: kuberde-cli config-ssh --server %s
# Usage: ssh <agent-id>   e.g. ssh kuberde-agent-admin-abc-ssh-8a37f662
Host kuberde-*
    ProxyCommand kuberde-cli connect %%n
    User root
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ServerAliveInterval 30
    ServerAliveCountMax 3
%s
`, sshConfigMarkerBegin, serverURL, sshConfigMarkerEnd)
}

// writeSSHConfig replaces the KubeRDE block in ~/.ssh/config, or appends it
// if no existing block is found.
func writeSSHConfig(block string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	sshDir := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(sshDir, 0700); err != nil {
		return err
	}
	configPath := filepath.Join(sshDir, "config")

	// Read existing config (tolerate file-not-found)
	existing, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	updated := replaceOrAppendBlock(string(existing), block)

	return os.WriteFile(configPath, []byte(updated), 0600)
}

// replaceOrAppendBlock replaces the section between the KubeRDE markers in
// existing with block, or appends block if no markers are found.
func replaceOrAppendBlock(existing, block string) string {
	var (
		out     strings.Builder
		scanner = bufio.NewScanner(strings.NewReader(existing))
		inside  bool
		written bool
	)

	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, sshConfigMarkerBegin) {
			inside = true
			// Write the new block in place of the old one.
			out.WriteString(block)
			written = true
			continue
		}
		if inside {
			if strings.HasPrefix(line, sshConfigMarkerEnd) {
				inside = false
			}
			continue
		}
		out.WriteString(line)
		out.WriteByte('\n')
	}

	if !written {
		// No existing block – append.
		if out.Len() > 0 && !strings.HasSuffix(out.String(), "\n\n") {
			out.WriteByte('\n')
		}
		out.WriteString(block)
	}

	return out.String()
}
